name:                cs30
version:             0.1.1.0
license:             AllRightsReserved
author:              sjcjoosten
maintainer:          sjcjoosten+github@gmail.com
extra-source-files:
    - data/*
dependencies:
    - base
    - containers
    - HTTP
    - extra
    - random
    - utf8-string
    - bytestring
    - directory
    - aeson
    - texmath
    - text
    - template-haskell
    - transformers
    - th-lift-instances
    - parser-combinators
    - megaparsec
ghc-options:
    - -Wall
    - -fwarn-tabs
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates

library:
    source-dirs: src

executables:
    cs30.cgi:
        source-dirs:  cgi
        main:         CGI.hs
        dependencies: 
            - SHA
            - base64-bytestring
            - time
            - cs30
            - unix
    serve:
        source-dirs:  serve
        main:         Serve.hs
        dependencies: 
            - warp
            - wai
            - wai-extra
            - http-types
            - mime-types
            - th-lift-instances
            - cs30
tests:
    spec:
        main:   test.hs
        source-dirs:
            - test
        dependencies: 
            - cs30
            - tasty
            - tasty-hunit
            - tasty-quickcheck
            - QuickCheck
            - texmath
            
